---
title: "linear_models"
author: "Leonor Rui"
date: "2024-11-07"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

Do some data cleaning

```{r}
data("nyc_airbnb")

nyc_airbnb = nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |>
  filter(borough != "Staten Island") |>
  select(price, stars, borough, neighborhood, room_type) |>
  ## change into order by frequency
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

## Fit some models

Start relatively simple

```{r}
fit = lm(price ~ stars, data = nyc_airbnb)

summary(fit)

names(summary(fit))

coef(fit)

## format the output into a dataframe
broom::tidy(fit)

fit |>
  broom::tidy() |>
  select(term, estimate, p.value)

fit |>
  broom::glance()
```

Try a bit more complex

R put each level of a categorical variable to be its own variable

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

fit |>
  broom::tidy() |>
  select(term, estimate, p.value) |>
  mutate(
    term = str_replace(term, "borough", "Borough:")
  ) |>
  knitr::kable(digits = 3)
```







